### ISSUE TITLE
MySQL connection timing out

### ISSUE THREAD

**Issue by uncovery** [uncovery/Unc_Plug#2]
Once the server is running for a while, the MySQL connection that is created in the main class is being closed. Once a lag event occurs, the data cannot be written to the DB anymore.

If anyone can help me how to re-open the MySQL connection when the command is being executed, it would be very helpful. I tried to get help for this and people suggested to use connection pooling with a tool like hikari but [just looking at it](https://www.stubbornjava.com/posts/database-connection-pooling-in-java-with-hikaricp) seems like overkill to me.  

Thanks!

**Comment by uncovery** [comment]
I tried to make the DB connection on-demand with the last commit, but now I get this error:

```
[12:01:27 WARN]: Unexpected exception while parsing console command "unc_chunks"
org.bukkit.command.CommandException: Unhandled exception executing command 'unc_chunks' in plugin UncPlug v1.0
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot.jar:git-Spigot-b6ecf3b-68b4fb6]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot.jar:git-Spigot-b6ecf3b-68b4fb6]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:648) ~[spigot.jar:git-Spigot-b6ecf3b-68b4fb6]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchServerCommand(CraftServer.java:634) [spigot.jar:git-Spigot-b6ecf3b-68b4fb6]
        at net.minecraft.server.v1_12_R1.DedicatedServer.aP(DedicatedServer.java:444) [spigot.jar:git-Spigot-b6ecf3b-68b4fb6]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:407) [spigot.jar:git-Spigot-b6ecf3b-68b4fb6]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot.jar:git-Spigot-b6ecf3b-68b4fb6]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot.jar:git-Spigot-b6ecf3b-68b4fb6]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]
Caused by: java.lang.NullPointerException
        at me.uncovery.uncplug.CommandListChunks.writeChunkData(CommandListChunks.java:154) ~[?:?]
        at me.uncovery.uncplug.CommandListChunks.getLoadedChunks(CommandListChunks.java:98) ~[?:?]
        at me.uncovery.uncplug.CommandListChunks.onCommand(CommandListChunks.java:42) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot.jar:git-Spigot-b6ecf3b-68b4fb6]
        ... 8 more
```

The error refers to the [first usage of the connection object](https://github.com/uncovery/Unc_Plug/blob/master/src/me/uncovery/uncplug/CommandListChunks.java#L154).

**Comment by uncovery** [comment]
Fixed with last commit
